version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - mynetwork

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      # فقط کد backend رو به داخل کانتینر منتقل کن
      - ./backend:/app/backend
    ports:
      - "8007:8000"
    container_name: planning_container
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend/my-app
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - web
    networks:
      - mynetwork


  

volumes:
  db_data: {}

networks:
  mynetwork:
    driver: bridge
